---
version: 0.2

environment_variables:
  plaintext:
    PACKAGE: "github.com/gezza-b/devopspro-prep"
    S3_BUCKET: "deploy-gez"


phases:
  install: 
    runtime-versions:
      golang: 1.13
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}" 
      # print env variables
      - env | sort
    finally:
      - echo End of install phase

  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      # Fetch all dependencies
      - go get -t ./...
      - go get -u golang.org/x/lint/golint

      - golint -set_exit_status
      - go test ./...
    finally:
      - echo End of pre_build phase

  build:
    commands:
      - echo Build started on `date`
      - echo Getting packages
      - go get ./...
      #- echo Compiling the Lambda code...
      - go build lambda/getdata/imghandler.go
      # Packaging with AWS SAM
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yml
      
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - imghandler
    - packaged.yml