AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build the image recognition app

Parameters:
  ImgBucket:
    Description: Bucket for image upload
    Type: String
    Default: imghandler-gez

Resources:
  ImgHandler:                                 # ImgHandler - triggered by S3 upload
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/imghandler
      Runtime: go1.x
      Timeout: 5
      MemorySize: 128
      Policies: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - RekognitionDetectOnlyPolicy: {}
        - SNSPublishMessagePolicy: 
            TopicName: AddImgTopic
        - S3ReadPolicy: 
            BucketName: !Ref ImgBucket
      Description: Function is triggered after S3 upload and collects image information
      Tags: 
        Name: imghandler
        Env: test
        Account: !Ref "AWS::AccountId"
        Region: !Ref "AWS::Region"
      Tracing: Active
      Events:
        ImgHandler:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
  WriteMetaData:                              # Write Meta Data - triggered by SNS
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/writedata
      Runtime: go1.x
      Timeout: 5
      Description: Function writes image information to DynamoDB
      Tags: 
        Name: writemetadata
        Env: test
        Account: !Ref "AWS::AccountId"
        Region: !Ref "AWS::Region"
      Tracing: Active
      Events:
        WriteMetaData:
          Type: SNS
          Properties: 
            Topic: 
              !Join
                - ''
                - - 'arn:aws:sns:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':AddImgTopic'

  SrcBucket:
    Type: AWS::S3::Bucket

Outputs:
  ImgHandler:
    Value: !Ref ImgHandler   
    Export: 
      Name: !Sub ${AWS::StackName}-ImgHandler
  ImgHandlerArn:
    Value: !GetAtt [ImgHandler, Arn]
    Export: 
      Name: !Sub ${AWS::StackName}-ImgHandlerArn  
  WriteMetaData:
    Value: !Ref WriteMetaData   
    Export: 
      Name: !Sub ${AWS::StackName}-WriteMetaData
  WriteMetaDataArn:
    Value: !GetAtt [WriteMetaData, Arn]
    Export: 
      Name: !Sub ${AWS::StackName}-WriteMetaDataArn
