# https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build the image recognition app
Resources:
  ImgHandler:                                 # ImgHandler - triggered by S3 upload
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/imghandler
      Runtime: go1.x
      Timeout: 5
      MemorySize: 128
      Events:
        ImgHandler:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
  WriteMetaData:                          # Write Meta Data - triggered by SNS
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/writedata
      Runtime: go1.x
      Timeout: 5
      Events:
        WriteMetaData:
          Type: SNS
          Properties: #arn:aws:sns:us-east-1:123456789012:AddImgTopic
            Topic: 
              !Join
                - ''
                - - 'arn:aws:sns:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':AddImgTopic'

  SrcBucket:
    Type: AWS::S3::Bucket
