# Deployment:
# aws cloudformation create-stack --stack-name codedeployDevopscert01 --template-body file://codedeploy-project-01.yml --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND

# aws cloudformation update-stack --stack-name codedeployDevopscert01 --template-body file://codedeploy-project-01.yml --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND

# aws cloudformation delete-stack --stack-name codedeployDevopscert01

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build the image recognition app

Resources:
  ImgHandlerFunction:
   Type: AWS::Serverless::Function
   Properties:
     Handler: bin/imghandler
     Runtime: go1.x
     CodeUri: s3://deploy-gez-useast/imghandler    #/CodeBuild01
     # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/automating-updates-to-serverless-apps.html
     AutoPublishAlias: live
     DeploymentPreference:
       Type: AllAtOnce
