AWSTemplateFormatVersion: 2010-09-09
Description: Creates an SQS queue to store image information
# Deployment:
# aws cloudformation create-stack --stack-name snsCataloguingDevopscert --template-body file://sns.yml 

# aws cloudformation delete-stack --stack-name snsCataloguingDevopscert 

# aws cloudformation update-stack --stack-name snsCataloguingDevopscert --template-body file://sns.yml 

Resources:
  AddImgTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AddImgTopic
      Tags: 
        - Key: Name
          Value: addimgtopic
        - Key: Env
          Value: test
      TopicName: "AddImgTopic"

Outputs:
  AddImgTopic:
    Value: !Ref AddImgTopic   # ARN
    Export: 
      Name: !Sub ${AWS::StackName}-AddImgTopic